#sql表语句
sql:
  tables:
    M_APPLICATION: CREATE TABLE "MSDM"."M_APPLICATION"(
      "ID" VARCHAR(255) NOT NULL,
      "NAME" VARCHAR(255),
      "CODE" VARCHAR(255) NOT NULL,
      "MACHINE_CODE" VARCHAR(255) NOT NULL,
      "LICENSE" VARCHAR(1024) NOT NULL,
      "CREATE_BY" VARCHAR(255) NOT NULL,
      "CREATE_TIME" TIMESTAMP(0) NOT NULL,
      "UPDATE_BY" VARCHAR(255),
      "UPDATE_TIME" TIMESTAMP(0),
      "REMARK" TEXT,
      NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);