server:
  port: 8099
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# 日志配置
logging:
  level:
    com.gg: debug
    org.springframework: warn
#ES配置
elasticsearch:
  scheme: http
  nodes: elasticsearch-dev.jcw.svc.cluster.local:9200
  username: elastic
  password: tbpMK7r1Gl3em1hQW8Ke
#SpringBoot-ES配置
spring:
  profiles:
    include: db,table-dm
  elasticsearch:
    rest:
      uris: http://9.135.95.39:9200,http://9.135.95.39:9201,http://9.135.95.39:9202
      #username: elastic
      #password: tbpMK7r1Gl3em1hQW8Ke